### PR TITLE
Updated .travis.yml file

### PR DESCRIPTION
**Pull request by jasnow**
Updated .travis.yml file by:
 * Changed 2.1.1 to 2.1.7.
 * Added 2.2.4
 * Added "cache: bundler" and "sudo: false" (newer options).

### CODE REVIEW

**Comment by jasnow** [comment]
Hopefully you welcome pull requests.

**Comment by jmondo** [comment]
thanks!

**Comment by jasnow** [comment]
@jmondo - Time to release an updated gem to rubygems.org ?

**Comment by jmondo** [comment]
Ah yes, indeed. Thanks.

**Comment by jmondo** [comment]
Done! Thanks for the reminder!

**Pull request merged**
